#!/bin/bash

#[ Script ]--------------------------------------------------------------------#
#                                                                              #
# check_certificate                                                            #
#                                                                              #
# PT-br:                                                                       #
# Checagem simples de Expiração de Certificado SSL para Nagios / Icinga        #
#                                                                              #
# ----------------------------                                                 #
#                                                                              #
# EN:                                                                          #
# Simple 'SSL Certificate Expiration' check for Nagios / Icinga                #
#                                                                              #
#------------------------------------------------------------------------------#
#                                                                              #
# Copyright (c) 2019 Reinaldo Marques de Lima reimlima@gmail.com               #
#                                                                              #
# PT-br:                                                                       #
# A permissão  é  concedida,  a título gratuito, a qualquer pessoa que obtenha #
# uma   cópia   deste   software   e   arquivos   de  documentação  associados #
# (o "Software"),  para  lidar  com  o  Software sem restrição, incluindo, sem #
# limitação,  os  direitos  de  usar,  copiar,  modificar,  mesclar, publicar, #
# distribuir,  sublicenciar,  e / ou vender cópias do Software, e permitir que #
# as  pessoas  a  quem  o  Software  é fornecido o façam, sujeito às seguintes #
# condições:                                                                   #
#                                                                              #
# O  aviso de copyright acima e este aviso de permissão devem ser incluídos em #
# todas as cópias ou partes substanciais do Software.                          #
#                                                                              #
# O  SOFTWARE É FORNECIDO "COMO ESTÁ", SEM GARANTIA DE QUALQUER TIPO, EXPRESSA #
# OU  IMPLÍCITA,  INCLUINDO,  SEM  LIMITAÇÃO, AS GARANTIAS DE COMERCIALIZAÇÃO, #
# ADEQUAÇÃO  A  UM  DETERMINADO  FIM E NÃO VIOLAÇÃO. EM NENHUM CASO OS AUTORES #
# OU  DIREITOS AUTORAIS TITULARES  SERÃO RESPONSÁVEIS POR QUALQUER RECLAMAÇÃO, #
# DANOS  OU  OUTRAS  RESPONSABILIDADES,  SEJA  EM  UMA  AÇÃO DE CUMPRIMENTO DE #
# CONTRATO OU DE OUTRA FORMA, DECORRENTE DE, OU EM CONEXÃO COM O SOFTWARE OU O #
# USO OU OUTRAS FUNÇÕES DO SOFTWARE.                                           #
#                                                                              #
# Exceto  conforme  contido no presente aviso, o nome do (s) dos detentores de #
# direitos  autorais acima não devem ser utilizados em publicidade ou de outra #
# forma  para  promover  a venda, uso ou outras negociações deste Software sem #
# autorização prévia por escrito.                                              #
#                                                                              #
# ----------------------------                                                 #
#                                                                              #
# EN:                                                                          #
# Permission is hereby granted, free of charge, to any person obtaining a copy #
# of  this  software  and  associated  documentation  files  (the "Software"), #
# to  deal  in  the Software without restriction, including without limitation #
# the  rights  to  use,  copy, modify, merge, publish, distribute, sublicense, #
# and/or  sell  copies  of  the  Software,  and  to permit persons to whom the #
# Software is furnished to do so, subject to the following conditions:         #
#                                                                              #
# The  above  copyright notice and this permission notice shall be included in #
# all copies or substantial portions of the Software.                          #
#                                                                              #
# THE  SOFTWARE  IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR #
# IMPLIED,  INCLUDING  BUT  NOT  LIMITED TO THE WARRANTIES OF MERCHANTABILITY, #
# FITNESS  FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE #
# AUTHORS  OR  COPYRIGHT  HOLDERS  BE  LIABLE  FOR ANY CLAIM, DAMAGES OR OTHER #
# LIABILITY,   WHETHER   IN   AN   ACTION  OF  CONTRACT,  TORT  OR  OTHERWISE, #
# ARISING FROM,  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER #
# DEALINGS IN THE SOFTWARE.                                                    #
#                                                                              #
# Except  as  contained  in  this  notice,  the name(s) of the above copyright #
# holders  shall  not be used in advertising or otherwise to promote the sale, #
# use or other dealings in this Software without prior written authorization.  #
#                                                                              #
#------------------------------------------------------------------------------#

#[ Variables ]-----------------------------------------------------------------#

AWK=$(which awk)
DATE=$(which date)
TAIL=$(which tail)
OPENSSL=$(which openssl)
SCRIPTNAME=$(basename $0)
NOWTIMESTAMP=$($DATE +%s)

#[ Functions ]-----------------------------------------------------------------#

exitFunc(){
        # Generic output function, show the message given,
        # and then exits with the given code.

        # Parse message and exit code
        EXITCODE=$(echo $@ | $AWK '{print $NF}')
        EXITMESSAGE=$(echo $@ | $AWK '{ $NF = ""; print $0}')
        echo "$EXITMESSAGE"
        exit $EXITCODE
}

usage(){
        echo "
        usage:
        $SCRIPTNAME -s <site> -w <warning> -c <critical>

        Example:
        $SCRIPTNAME -s google.com -w 30 -c 15
        "
        exitFunc "Invalide Arguments given 1"
}

getExpirationDate(){
	EXPIRATIONDATE=$(echo | $OPENSSL s_client -servername $SITE -connect $SITE:443 2>/dev/null | $OPENSSL x509 -noout -dates | $TAIL -1 | $AWK -F= '{print $2}')
	if [[ ! $EXPIRATIONDATE ]]; then
		EXPIRATIONDATE="none"
	else
		EXPIRATIONTOSEC=$(date -d "$EXPIRATIONDATE" +%s)
	fi
	return $EXPIRATIONTOSEC
}

statusGenerate(){
	if [[ $EXPIRATIONMINUS30 -gt $NOWTIMESTAMP ]]; then
		RETURNCODE=0
	fi
	if [[ $EXPIRATIONMINUS30 -le $NOWTIMESTAMP ]]; then
		RETURNCODE=1
	fi
	if [[ $EXPIRATIONMINUS15 -le $NOWTIMESTAMP ]]; then
		RETURNCODE=2
	fi
	return $RETURNCODE
}

executionFlow(){
	WARNINGTOSEC=$(echo "$WARNING*86400" | bc)
	CRITICALTOSEC=$(echo "$CRITICAL*86400" | bc)
	getExpirationDate $SITE
	if [[ $EXPIRATIONDATE == "none" ]]; then
		exitFunc "Unable to fetch certificate's expiration date to the site $SITE 1"
	fi
	EXPIRATIONMINUS30=$(echo "${EXPIRATIONTOSEC}-${WARNINGTOSEC}" | bc)
	EXPIRATIONMINUS15=$(echo "${EXPIRATIONTOSEC}-${CRITICALTOSEC}" | bc)
	statusGenerate $EXPIRATIONMINUS15 $EXPIRATIONMINUS30
	if [[ $RETURNCODE == "0" ]]; then
		RETURNOUTPUT="OK"
	elif [[ $RETURNCODE == "1" ]] ; then
		RETURNOUTPUT="WARNING"
	else
		RETURNOUTPUT="CRITICAL"
	fi
	OUTPUTMSG="${RETURNOUTPUT}: Certificate Status from site $SITE is $RETURNOUTPUT. Expiration Date: $EXPIRATIONDATE $RETURNCODE"
	exitFunc $OUTPUTMSG
}

#[ Load commandline options ]--------------------------------------------------#

[[ $# -ne 6 ]] && usage

while getopts "s:w:c:" opts ; do
        case $opts in
                s) SITE=$OPTARG ;;
                w) WARNING=$OPTARG ;;
                c) CRITICAL=$OPTARG ;;
                *) usage ;;
        esac
done

executionFlow $@
